name: oppgave_16
on: 
  push:
    branches:
      - main
      - production
    paths:
      - src/oppgave_10.ps1
  workflow_dispatch:

jobs:
  job1:
    defaults:
      run:
        shell: pwsh
    runs-on: ubuntu-latest
    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
         creds: ${{secrets.GIDETVIDERE}}
         enable-AzPSSession: true

      - name: Azure Powershell
        uses: Azure/powershell@v1
        run: |
          ./src/oppgave_10.ps1 -UrlKortstokk 'http://nav-deckofcards.herokuapp.com/shuffle'
          azPSVersion: "latest"